name: Attaboysupplyco
favicon: null
layout_spectrum: 0.25817
typography_spectrum: 0.40109
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f8bad5'
    - '#fdecf3'
    - '#fbdeea'
    - '#f9cde0'
  brandStrength: 0.75
  lightness: 0.7334116632118821
  saturation: 0.39584955945611
  rhythmicContrast: 0.26017983141355217
purpose: []
